name: DataMiner CICD NuGet Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events.
  push:
    branches: []
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-tests:
    name: Run all tests (Ubuntu)
    runs-on: ubuntu-22.04 # Latest misses mono for .NET Framework
    env:
      DOWNLOAD_KEY: ${{ secrets.DOWNLOAD_KEY }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: dotnet test -c Release

  CICD:
    needs: ubuntu-tests
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.Sdk
    secrets:
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
      pfx: ${{ secrets.PFX }}
      pfxPassword: ${{ secrets.PFXPASSWORD }}
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}
