name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:
  dotnet-test:
    name: Run Integration Tests
    runs-on: windows-latest
    env:
      DOWNLOAD_KEY: ${{ secrets.DOWNLOAD_KEY }}

    steps:
      - uses: actions/checkout@v6

      - name: Integration Tests
        run: dotnet test -c Release --filter TestCategory=IntegrationTest

  CICD:
    needs: [dotnet-test]
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Master Workflow.yml@main
    with:
      sonarcloud-project-name: SkylineCommunications_Skyline.DataMiner.Sdk
      nuget-push-source: https://api.nuget.org/v3/index.json
      runs-on: windows-latest
      solution-filter-name: Skyline.DataMiner.Sdk.sln
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
